language: php
php:
  - '7.1'
  - nightly

before_script:
  - printf "\n" | pecl install yaml
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install -n --dev